services:
  frontend:
    build:
      context: .
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - .:/frontend
    command: sh -c "npm install && npx vite --host 0.0.0.0 --port 5173"
    networks:
      - app_net