services:
  booking-service:
    &booking-service
    build: ./booking-service
    restart: always
    volumes:
      - ./booking-service:/booking-service
    working_dir: /booking-service
    environment:
      - PYTHONPATH=src
      - BOOKING_DB_USER=${BOOKING_DB_USER}
      - BOOKING_DB_PASSWORD=${BOOKING_DB_PASSWORD}
      - BOOKING_DB_HOST=${BOOKING_DB_HOST}
      - BOOKING_DB_PORT=${BOOKING_DB_PORT}
      - BOOKING_DB_NAME=${BOOKING_DB_NAME}
      - BOOKING_APP_HOST=${BOOKING_APP_HOST}
      - BOOKING_APP_PORT=${BOOKING_APP_PORT}
      - BOOKING_APP_MODE=${BOOKING_APP_MODE}
    command: sh -c "alembic upgrade head  && uvicorn booking_api.main:create_app --factory --host ${BOOKING_APP_HOST} --port ${BOOKING_APP_PORT} --reload"
    ports:
      - "${BOOKING_APP_PORT}:${BOOKING_APP_PORT}"
    depends_on:
      booking-service-postgres:
        condition: service_healthy
    networks:
      - app_net

  booking-service-postgres:
    image: postgres:17-alpine
    volumes:
      - booking-service-postgres-data:/var/lib/postgresql/data
    ports:
      - "${BOOKING_DB_PORT}:${BOOKING_DB_PORT}"
    environment:
      - POSTGRES_DB=${BOOKING_DB_NAME}
      - POSTGRES_USER=${BOOKING_DB_USER}
      - POSTGRES_PASSWORD=${BOOKING_DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${BOOKING_DB_USER} -d ${BOOKING_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_net
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:26.8
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      - KC_DB=${KC_DB}
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_HOSTNAME_STRICT=${KC_HOSTNAME_STRICT}
      - KC_HTTP_ENABLED=${KC_HTTP_ENABLED}
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    networks:
      - app_net

  keycloak-postgres:
    image: postgres:17-alpine
    container_name: keycloak-postgres
    environment:
      - POSTGRES_DB=${KC_POSTGRES_DB}
      - POSTGRES_USER=${KC_POSTGRES_DB}
      - POSTGRES_PASSWORD=${KC_POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KC_POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - keycloak-postgres-data:/var/lib/postgresql/data
    networks:
      - app_net

  krakend:
    image: devopsfaith/krakend:2.7
    container_name: krakend
    command: ["run", "-c", "/etc/krakend/krakend.json", "-d"]
    volumes:
      - ./krakend/krakend.json:/etc/krakend/krakend.json:ro
    ports:
      - "8080:8080"
    depends_on:
      - keycloak
      - booking-service
    networks:
      - app_net


networks:
  app_net:
    driver: bridge

volumes:
  booking-service-postgres-data:
  keycloak-postgres-data:
