services:
  booking-service:
    &booking-service
    build: ./booking-service
    restart: always
    volumes:
      - ./booking-service:/booking-service
    working_dir: /booking-service
    environment:
      - PYTHONPATH=src
      - BOOKING_DB_USER=${BOOKING_DB_USER}
      - BOOKING_DB_PASSWORD=${BOOKING_DB_PASSWORD}
      - BOOKING_DB_HOST=${BOOKING_DB_HOST}
      - BOOKING_DB_PORT=${BOOKING_DB_PORT}
      - BOOKING_DB_NAME=${BOOKING_DB_NAME}
      - BOOKING_APP_HOST=${BOOKING_APP_HOST}
      - BOOKING_APP_PORT=${BOOKING_APP_PORT}
      - BOOKING_APP_MODE=${BOOKING_APP_MODE}
    command: sh -c "alembic upgrade head  && uvicorn booking_api.main:create_app --factory --host ${BOOKING_APP_HOST} --port ${BOOKING_APP_PORT} --reload"
    ports:
      - "${BOOKING_APP_PORT}:${BOOKING_APP_PORT}"
    depends_on:
      booking-service-postgres:
        condition: service_healthy
    networks:
      - app_net

  booking-service-postgres:
    image: postgres:17-alpine
    volumes:
      - booking-service-postgres-data:/var/lib/postgresql/data
    ports:
      - "${BOOKING_DB_PORT}:${BOOKING_DB_PORT}"
    environment:
      - POSTGRES_DB=${BOOKING_DB_NAME}
      - POSTGRES_USER=${BOOKING_DB_USER}
      - POSTGRES_PASSWORD=${BOOKING_DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${BOOKING_DB_USER} -d ${BOOKING_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_net
    restart: always

networks:
  app_net:
    driver: bridge

volumes:
  booking-service-postgres-data:
