"""add unique category name

Revision ID: 2b372ec93866
Revises: 9d3f6f1caf2b
Create Date: 2026-10-04 10:41:02.341209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b372ec93866'
down_revision: Union[str, Sequence[str], None] = '9d3f6f1caf2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        """
        DO $$ BEGIN
            IF EXISTS (
                SELECT 1 FROM categiries WHERE btrim(name) = ''
            ) THEN
                RAISE EXCEPTION 'Cannot add category name constraint: blank category names exist';
            END IF;
            IF EXISTS (
                SELECT btrim(name)
                FROM categiries
                GROUP BY btrim(name)
                HAVING count(*) > 1
            ) THEN
                RAISE EXCEPTION 'Cannot add category name constraint: duplicate category names exist';
            END IF;
        END $$;
        """
    )
    op.execute("UPDATE categiries SET name = btrim(name)")
    op.create_unique_constraint('uq_categiries_name', 'categiries', ['name'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_categiries_name', 'categiries', type_='unique')
    # ### end Alembic commands ###
